// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTJ9nJxdg9wc7e4-sG0g0Ib8r6e5lNEXM',
    appId: '1:712670080424:ios:fbca557bb9bce8d19d819d',
    messagingSenderId: '712670080424',
    projectId: 'diario-personal-af90c',
    storageBucket: 'diario-personal-af90c.firebasestorage.app',
    iosBundleId: 'com.example.ejemplo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTJ9nJxdg9wc7e4-sG0g0Ib8r6e5lNEXM',
    appId: '1:712670080424:ios:fbca557bb9bce8d19d819d',
    messagingSenderId: '712670080424',
    projectId: 'diario-personal-af90c',
    storageBucket: 'diario-personal-af90c.firebasestorage.app',
    iosBundleId: 'com.example.ejemplo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRu9cb7xUDKAnGTsY4quZn6HPgzN-010',
    appId: '1:712670080424:web:73818e483a20f3849d819d',
    messagingSenderId: '712670080424',
    projectId: 'diario-personal-af90c',
    authDomain: 'diario-personal-af90c.firebaseapp.com',
    storageBucket: 'diario-personal-af90c.firebasestorage.app',
    measurementId: 'G-9W5RHY6F5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcet1ftOV7ykQSnigoODYbuo0gCYUtQhI',
    appId: '1:712670080424:android:df308f58e863b18d9d819d',
    messagingSenderId: '712670080424',
    projectId: 'diario-personal-af90c',
    storageBucket: 'diario-personal-af90c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoRu9cb7xUDKAnGTsY4quZn6HPgzN-010',
    appId: '1:712670080424:web:8de713bb2e54b1a29d819d',
    messagingSenderId: '712670080424',
    projectId: 'diario-personal-af90c',
    authDomain: 'diario-personal-af90c.firebaseapp.com',
    storageBucket: 'diario-personal-af90c.firebasestorage.app',
    measurementId: 'G-MEWLYJHSSB',
  );

}